### ISSUE TITLE
print plug-in

### ISSUE THREAD

**Issue by sandrocol** [MapWindow/MapWindow5#1]
when I use the print plug-in, the toolbar on the right of the image (with elements and properties) doesn't work; it is not active.

**Comment by pmeems** [comment]
Do you have loaded any layers? 
Which version of MW5 are you using?
I just tried and I don't have the problems you are mentioning:
![image](https://cloud.githubusercontent.com/assets/12067729/18043127/1b042900-6dc6-11e6-823a-c3041243c73d.png)


--
Paul

**Comment by sandrocol** [comment]
Thank you for the answer. The version is the one in the screenshot attached. I tried again after your answer, but it is the same. For instance it is impossible to change the units of the scale.
![attachment1](https://cloud.githubusercontent.com/assets/21082509/18059276/985f54e0-6e18-11e6-8eb8-c1161b2ac7e9.jpg)
![attachement2](https://cloud.githubusercontent.com/assets/21082509/18059319/c30dfb4c-6e18-11e6-8389-ecdcafff8c81.jpg)
Sandro

**Comment by pmeems** [comment]
Perhaps you can mail me because I still don't have this problem: bontepaarden[AT]gmail[D0T]com
I open a shapefile. Hit the Print button. In the print layout window I adjust the map size and add a scale bar. Next I select the map again and change its scale. The map is zoomed and the scale bar is adjusted.

Perhaps you forgot to select the map element again? In your last screenshot you still have the scalebar element selected.

**Comment by sandrocol** [comment]
the problem is that the bar on the right with "elements" and "properties" doesn't work. for instance, if I add a "north arrow" and want to modify its default symbol, I cannot because the bar il blocked.
an other example. in the screenshot of my post I selected the scal-bar because I wanted change it from miles into meters, but i could'nt for the same reason.

**Comment by pmeems** [comment]
I don't have these issues either.
Do you have this with all your datasets or just this one? Can you send me your dataset?
I'm testing with the Newton shapefile from the Newton sample project. Do you also have that dataset?
If so could you try with that dataset and let me know?

**Comment by sandrocol** [comment]
I tried as you told me (see attachement), but it is the same. now I disinstall the program and install it again, and then i'll let you know.
thanks a lot for your attention
![fig](https://cloud.githubusercontent.com/assets/21082509/18159031/1a544f2c-7027-11e6-9443-8f960f11c3f2.jpg)

**Comment by sandrocol** [comment]
I disinstalled MW5 and reloaded again, but nothing changed

**Comment by pmeems** [comment]
Please send me your dataset and I'll try with it.

**Comment by pmeems** [comment]
Hi Sandro,

I tested with your data and I don't have the problems you mention.
Perhaps you can look at the log file, it might tells something.

I also noticed your .prj file is not recognized as a known projection. Do you have the EPSG number?

**Comment by sandrocol** [comment]
thank you Paul; the EPSG number is 3004 Monte Mario Italy Zone 2. I will check the log file.




----Messaggio originale----

Da: "Paul Meems" <notifications@github.com>

Data: 27/09/2016 15.12

A: "MapWindow/MapWindow5"<MapWindow5@noreply.github.com>

Cc: "sandrocol"<colussa.sandro@libero.it>, "State change"<state_change@noreply.github.com>

Ogg: Re: [MapWindow/MapWindow5] print plug-in (#1)




Hi Sandro,


I tested with your data and I don't have the problems you mention.

Perhaps you can look at the log file, it might tells something.


I also noticed your .prj file is not recognized as a known projection. Do you have the EPSG number?

**Comment by pmeems** [comment]
Closing this old request for help.
