### ISSUE TITLE
Read Only Coordinate X and Y Properties?

### ISSUE THREAD

**Issue by dhuantes** [MapWindow/MapWindow5#10]
Was wondering why the X and Y properties of the Coordinate class were read only.  I have a few use cases where I allow users to move coordinates.  I had to obtain the InternalObject to do this. When I have time I will look at the Shape Editor Plugin to see how it handles this.  There may be a good reason for this but it's not obvious to me right now.  Thanks.

**Comment by pmeems** [comment]
I created https://mapwindow.atlassian.net/browse/CORE-195
Will try to fix it soon.

**Comment by pmeems** [comment]
I've just committed a fix for this issue. Please pull the latest version and let me know if this solves your problem.
A longer description of this fix can be found at https://mapwindow.atlassian.net/browse/CORE-195
