### ISSUE TITLE
How to create a shape file from sql query

### ISSUE THREAD

**Issue by saadb** [MapWindow/MapWindow5#108]
How can I create a shape file from an SQL query like Postgis' program pgsql2shp

**Comment by pmeems** [comment]
It is best to ask questions on our forum: https://mapwindow.discourse.group/

Have a look at [FileManager.OpenFromDatabase()](https://www.mapwindow.org/documentation/mapwingis4.9/class_file_manager.html#a6454319829fa91ed7e2c453fcc769827)
