### ISSUE TITLE
Map5 query selection color

### ISSUE THREAD

**Issue by ralphkopp** [MapWindow/MapWindow5#11]
I have a layer of polygons and I want to select those polygons where

![query1](https://cloud.githubusercontent.com/assets/26418318/23919878/2aad0eb0-08be-11e7-81eb-91ae18e95d65.JPG)

and the result I get is below where the selected polygons are yellow.  This is fine, but how do I change selection color to something else, like red.  I could not find an option for doing so.  Thanks for your help.

![query2](https://cloud.githubusercontent.com/assets/26418318/23919886/338e500c-08be-11e7-91db-b175bcda704d.JPG)

**Comment by pmeems** [comment]
You are right. in MW5 you can't set the selection color.
Do you want to set the selection color of all selections or do you want to set the color only for the query results?

**Comment by pmeems** [comment]
I added a color picker to the selection options form.
See screenshot in https://mapwindow.atlassian.net/browse/CORE-196

**Comment by ralphkopp** [comment]
HiI wanted to set the color just for query results.  I see from your other emails that you have made a change.  Thanks for your help.Ralph
