### ISSUE TITLE
mapwingis get elevation or height from shapefile

### ISSUE THREAD

**Issue by noone77777** [MapWindow/MapWindow5#112]
how mapwingis get elevation or height from shapefile ?

**Comment by pmeems** [comment]
Questions can best be asked at the forum: https://mapwindow.discourse.group/
If you have a 3d Shapefile you can access the Z-coordinate: [Poins.Z](https://www.mapwindow.org/documentation/mapwingis4.9/class_point.html#a588ab2cc4cf2be513c5de5a7756e74f2)
