### ISSUE TITLE
In Mapwindow5 is possible work with HIDROSIG

### ISSUE THREAD

**Issue by CharlesArthur** [MapWindow/MapWindow5#12]

**Comment by pmeems** [comment]
Can you explain a bit more.
What is HIDROSIG?

**Comment by CharlesArthur** [comment]
Hidrosig 4.0 is a plugin of hidrology, this plugin worked with mapwindow
4.6, but in windows 10 no work. Is possible integrate HIDROSIG with the
mapwindow5 and work in windows 10. Can view
http://minas.medellin.unal.edu.co/departamentos/geocienciasymedioambiente/hidrosig/es/


2017-05-11 2:35 GMT-05:00 Paul Meems <notifications@github.com>:

**Comment by pmeems** [comment]
MW4.* plug-ins don't work out of the box with MW5.
Parts need to be rewritten. If you have funding for this we can implement it.
