### ISSUE TITLE
World_Data_Grids.mwprj

### ISSUE THREAD

**Issue by diospyros** [MapWindow/MapWindow5#14]
Downloaded the project file World_Data_Grids.mwprj from 

http://www.waterbase.org/download_data.html

But MapWin gives an error when trying to open it.

Is this a bug or am I doing something wrong?

**Comment by pmeems** [comment]
Which version of MW are you using? What is the error?
I think the project file is made for an old version of MW4.

**Comment by pmeems** [comment]
No response for months. Closing this issue.
