### ISSUE TITLE
Problem with add layer from image

### ISSUE THREAD

**Issue by tantdhvan** [MapWindow/MapWindow5#15]
I am using MapWinGIS4.9. When I add a layer from image, the scale of the map is incorrect. How can I adjust the scale to the correct one or edit the image before add layer? 
Thanks you for help!

**Comment by pmeems** [comment]
How did you create this image? Is it a png-file or Tiff. Does it have a world file?
Can you attach the image file and another file to show the incorrect scale?

**Comment by pmeems** [comment]
No response for months. Closing this issue.

**Comment by nguyenthetan1995** [comment]
anh tân trần có thể giúp em một số vấn đề về mapwingis đc không ạ?
