### ISSUE TITLE
axMap.DrawLabel problem

### ISSUE THREAD

**Issue by jan-sv** [MapWindow/MapWindow5#16]
[Form1.cs.txt](https://github.com/MapWindow/MapWindow5/files/1295446/Form1.cs.txt)
![error1](https://user-images.githubusercontent.com/31884101/30318824-d7ba63d2-97b6-11e7-8f69-b31f28114931.jpg)
I am using precompiled MapWinGis version 4.9.4.2 with Delphi7, Vs2013 VB and VS2013 C#
I have attached C# example
When I comment line with DrawLabel statement , all is Ok.  when uncomment this line, project crashes.

**Comment by pmeems** [comment]
This issue was moved to MapWindow/MapWinGIS#39
