### ISSUE TITLE
Silent installer issue for MapWindow5

### ISSUE THREAD

**Issue by pnrthomp** [MapWindow/MapWindow5#17]
Hi,

I'm trying to perform a silent installation for MapWindow-v5.1.1.0-Win32.exe and it runs into an issue.  The Visual C++ Redistributable (x86) - 12.0.30501 will pop up looking for user input. 

After troubleshooting the installer I found that the Visual C++ Redistributable (x86) - 12.0.30501 that is executed uses the option of /qb . This option is no longer used for this installer. For it to work as intended, the options are /passive or /quiet.

Could the installer command line be updated to use /passive or /quiet instead?

Thanks.

**Comment by pmeems** [comment]
Thanks for catching this. I've created https://mapwindow.atlassian.net/browse/MW5CORE-202 for this and will modify it before the next release.

**Comment by pmeems** [comment]
This was already fixed in v5.2
