### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by PierreArchambeau** [MapWindow/MapWindow5#19]
Hi,
I would like to open the solution into Visual Studio 2017 Community Edition but it fails to compile due to changes in the NuGet packages manager.
Do you plan to support VS2017 soon?
Thanks

**Comment by pmeems** [comment]
We've just released MapWinGIS v4.9.5. When no problems are found by the community we will make a new MW5 version and after that we plan to upgrade to VS2017.

**Comment by PierreArchambeau** [comment]
I understand.
Maybe I can contribute once upgraded to VS2017.
I'm very interested in the project.

**Comment by pmeems** [comment]
We can always use more contributors.
You can start by creating pull requests and when they are of a good quality we can give you direct GIT access.

**Comment by pmeems** [comment]
Closing for now.
