### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by dhuantes** [MapWindow/MapWindow5#2]
I downloaded and installed MapWindow-v5.1.10-x64.exe on a Windows 7 64bit machine.  I am having several issues.

1. My regular login does not have Admin privileges so the initial attempt failed when the installer tried to create the MapWindow5 directory in "C:\Program Files" folder.
2. Installing with non-Admin account to C:\MapWindow5 was almost successful (at least didn't have any problems writing there) but one of the final things the installer does is to update the registry with several keys and all of these attempts failed.
3. I was able to install "successfully" when I run the installation as an Administrator.  Unfortunately, since it was installed under an Admin account all the configurations seemed to be keyed to the Admin account profile used for the installation.  For example, none of the repositories are shown in the Repository window docked on the right side of the App.  Additionally, I can add a Shapefile as a layer but I can't edit properties because the properties context menu option never shows a dialog.
4. So with my installation the only way I can run MapWindow5 and get full functionality is by running it as an Administrator.  This is ok as a temporary fix but end users of my plugin have far less privileges then I do so will never be able to run MapWindow5 with the current installer.  Maybe an installation option to "Install for All Users" would correct the problem.

I am open to suggestions and other workarounds but seamless installation would be preferred.  Thanks for all the work.  It looks great!

**Comment by pmeems** [comment]
Thanks Dan for letting us know.
In two weeks time we have a code-sprint and we'll have a look at this issue.
I copied your issue to https://mapwindow.atlassian.net/browse/CORE-176

--
Paul

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
