### ISSUE TITLE
Aritmetic Error on load app, Windows 10, Two HighDPI monitors

### ISSUE THREAD

**Issue by softcanondev** [MapWindow/MapWindow5#20]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: form
   at Syncfusion.Windows.Forms.Tools.XPMenus.FormNativeWindow..ctor(Form form)
   at Syncfusion.Windows.Forms.Tools.XPMenus.MainFrameBarManager.SubscribeFormNativeWnd()
   at Syncfusion.Windows.Forms.Tools.XPMenus.MainFrameBarManager.Form_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at Syncfusion.Windows.Forms.MetroForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MapWindow
    Assembly Version: 5.1.1.28951
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MapWindow.exe
----------------------------------------
MW5.Services
    Assembly Version: 5.1.1.28941
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Services.DLL
----------------------------------------
MW5.Shared
    Assembly Version: 5.1.1.28935
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Shared.DLL
----------------------------------------
MW5.Plugins
    Assembly Version: 5.1.1.28937
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Plugins.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MW5.DI.Castle
    Assembly Version: 5.1.1.28938
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.DI.Castle.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
log4net
    Assembly Version: 1.2.15.0
    Win32 Version: 1.2.15.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/log4net.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Castle.Windsor
    Assembly Version: 3.3.0.0
    Win32 Version: 3.3.0.51
    CodeBase: file:///C:/Program%20Files/MapWindow5/Castle.Windsor.DLL
----------------------------------------
Castle.Core
    Assembly Version: 3.3.0.0
    Win32 Version: 3.3.3.58
    CodeBase: file:///C:/Program%20Files/MapWindow5/Castle.Core.DLL
----------------------------------------
MW5.UI
    Assembly Version: 5.1.1.28937
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.UI.DLL
----------------------------------------
Syncfusion.Shared.Base
    Assembly Version: 14.1450.0.46
    Win32 Version: 14.1450.0.46
    CodeBase: file:///C:/Program%20Files/MapWindow5/Syncfusion.Shared.Base.DLL
----------------------------------------
MW5.Api
    Assembly Version: 5.1.1.28936
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Api.DLL
----------------------------------------
MW5.Projections
    Assembly Version: 5.1.1.28939
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Projections.DLL
----------------------------------------
MW5.Data
    Assembly Version: 5.1.1.28939
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Data.DLL
----------------------------------------
MW5.Tools
    Assembly Version: 5.1.1.28943
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Tools.DLL
----------------------------------------
MW5.Gdal
    Assembly Version: 5.1.1.28944
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Gdal.DLL
----------------------------------------
MW5.Attributes
    Assembly Version: 5.1.1.28940
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Attributes.DLL
----------------------------------------
MW5.Tiles
    Assembly Version: 5.1.1.28939
    Win32 Version: 5.1.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/MW5.Tiles.DLL
----------------------------------------
Syncfusion.GridHelperClasses.Windows
    Assembly Version: 14.1450.0.46
    Win32 Version: 14.1450.0.46
    CodeBase: file:///C:/Program%20Files/MapWindow5/Syncfusion.GridHelperClasses.Windows.DLL
----------------------------------------
Syncfusion.Grid.Grouping.Windows
    Assembly Version: 14.1450.0.46
    Win32 Version: 14.1450.0.46
    CodeBase: file:///C:/Program%20Files/MapWindow5/Syncfusion.Grid.Grouping.Windows.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Syncfusion.Tools.Windows
    Assembly Version: 14.1450.0.46
    Win32 Version: 14.1450.0.46
    CodeBase: file:///C:/Program%20Files/MapWindow5/Syncfusion.Tools.Windows.DLL
----------------------------------------
Interop.MapWinGIS
    Assembly Version: 4.9.0.0
    Win32 Version: 4.9.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Interop.MapWinGIS.DLL
----------------------------------------
AxInterop.MapWinGIS
    Assembly Version: 4.9.0.0
    Win32 Version: 4.9.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/AxInterop.MapWinGIS.DLL
----------------------------------------
Syncfusion.Grid.Windows
    Assembly Version: 14.1450.0.46
    Win32 Version: 14.1450.0.46
    CodeBase: file:///C:/Program%20Files/MapWindow5/Syncfusion.Grid.Windows.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.101.0
    Win32 Version: 1.0.101.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Syncfusion.Grouping.Base
    Assembly Version: 14.1450.0.46
    Win32 Version: 14.1450.0.46
    CodeBase: file:///C:/Program%20Files/MapWindow5/Syncfusion.Grouping.Base.DLL
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
MW5.DebugWindow
    Assembly Version: 0.0.1.28943
    Win32 Version: 0.0.1.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.DebugWindow.DLL
----------------------------------------
MW5.Identifier
    Assembly Version: 1.0.0.28942
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.Identifier.DLL
----------------------------------------
MW5.ImageRegistration
    Assembly Version: 1.0.0.28948
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.ImageRegistration.DLL
----------------------------------------
MW5.Printing
    Assembly Version: 1.0.0.28940
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.Printing.DLL
----------------------------------------
MW5.Repository
    Assembly Version: 1.0.0.28942
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.Repository.DLL
----------------------------------------
MW5.ShapeEditor
    Assembly Version: 1.0.0.28943
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.ShapeEditor.DLL
----------------------------------------
MW5.Symbology
    Assembly Version: 1.0.0.28943
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.Symbology.DLL
----------------------------------------
MW5.Symbology.XmlSerializers
    Assembly Version: 1.0.0.28943
    Win32 Version: 1.0.0.28943
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.Symbology.XmlSerializers.DLL
----------------------------------------
MW5.TableEditor
    Assembly Version: 1.0.0.28941
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.TableEditor.DLL
----------------------------------------
MW5.Toolbox
    Assembly Version: 1.0.0.28946
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Plugins/MW5.Toolbox.DLL
----------------------------------------
Equin.ApplicationFramework.BindingListView
    Assembly Version: 1.2.6009.28935
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Program%20Files/MapWindow5/Equin.ApplicationFramework.BindingListView.DLL
----------------------------------------
MetadataViewProxies_d5c5860c-9f8c-4609-9af1-389f5d17a325
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2558.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Runtime.Serialization.Formatters.Soap
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization.Formatters.Soap/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Serialization.Formatters.Soap.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by softcanondev** [comment]
at Syncfusion.Drawing.DrawingUtils.NCPaintHelper(Control control, INonClientPaintingSupport ncPaintDelegate, Message& m)
   at Syncfusion.Windows.Forms.ScrollControl.WmNcPaint(Message& msg)
   at Syncfusion.Windows.Forms.ScrollControl.WndProc(Message& msg)
   at Syncfusion.Windows.Forms.Tools.TreeViewAdv.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by pmeems** [comment]
You get this error on startup?
Your Win10 is up-to-date?

**Comment by softcanondev** [comment]
Yes, the latest version of windows 10, at startup

OS Name	Microsoft Windows 10 Pro
Version	10.0.16299 Build 16299
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	HP
System Model	HP ENVY m6 Notebook
System Type	x64-based PC
System SKU	M1W24UAR#ABA
Processor	AMD FX-8800P Radeon R7, 12 Compute Cores 4C+8G, 2100 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Insyde F.14, 28/3/2016
SMBIOS Version	2.8
Embedded Controller Version	80.35
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Binding Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.16299.248"
User Name	PORTATILJAVIER-\JAVIER
Time Zone	SA Pacific Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.0 GB
Available Physical Memory	7.50 GB
Total Virtual Memory	29.9 GB
Available Virtual Memory	20.2 GB
Page File Space	15.0 GB
Page File	C:\pagefile.sys
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Reasons for failed automatic device encryption: Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

![error mapwindow 5 windows 10 hdpi](https://user-images.githubusercontent.com/30165371/36384862-c367f0e0-155e-11e8-91e5-b9b23e12350a.jpg)

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
