### ISSUE TITLE
Tiles not loading / showing in MapWindow5

### ISSUE THREAD

**Issue by mmmakka** [MapWindow/MapWindow5#22]
Hey All

I am using MapWindow and are confronted with OpenStreetMap tiles not loading / showing when I am on a company network. 
1) When at the company network I type in the "test site" https://tile.openstreetmap.org/7/26/50.png directly into a browser, the tile shows in the browser. 
2) At home when using MapWindow with the same shapefile and using my own laptop and own network everything works fine and the tiles appear in the application.

I assume that I have to set a proxyserver setting, but I am not sure if that is the solution. And if that is the solution, I have no clue what it should be.

Any pointer would be truly appreciated!

Kind regards
M

**Comment by pmeems** [comment]
Go to Tools --> Settings:
![image](https://user-images.githubusercontent.com/12067729/35722475-c36dc40e-07f6-11e8-8a21-e6d2e8b14ca5.png)

Go to the Data --> TMS tab and fill in the settings:
![image](https://user-images.githubusercontent.com/12067729/35722515-eb12600a-07f6-11e8-8c4e-40c200064c52.png)
