### ISSUE TITLE
Chinese Character Labeling Error. Need Help.

### ISSUE THREAD

**Issue by wanghanbo** [MapWindow/MapWindow5#23]
Hello! Sorry for my English.
I'm trying to create labels on the map from my SQLite database, but it turned out that the encoding of the Russian language is not supported.
I Checked the SQLIte database. The field "FileName" in Tmpcadd table has chinese character and saved by unicode. But when I use [MapWindow5] to load and Label the field, the label text error occured like following image。  

Using SQLite Expert to view TmpCadd(encoding is utf-8),FileName field is correct.
![image](https://user-images.githubusercontent.com/5698893/35719000-0448ad74-0822-11e8-8efe-d80e0d0b023e.png)
So I run MapWindow 5 to load TmpCadd and labeling it by FileName field, chinese charater is error:
![image](https://user-images.githubusercontent.com/5698893/35719033-30dd63b6-0822-11e8-9089-d777ff27b9af.png)
I checked [filename] field and found labeling text is as same as SQLite expert's error when encoding is ANSI as following.
![image](https://user-images.githubusercontent.com/5698893/35719077-77c14a68-0822-11e8-9803-a9b9ebbb51d9.png)
![image](https://user-images.githubusercontent.com/5698893/35719082-826de390-0822-11e8-9062-fcee9e513c92.png)
What can I do?
[tempdb.zip](https://github.com/MapWindow/MapWindow5/files/1688293/tempdb.zip)

**Comment by pmeems** [comment]
See my answer at https://github.com/MapWindow/MapWinGIS/issues/68
No need to cross post questions.
