### ISSUE TITLE
when i link postgis,chinese show error

### ISSUE THREAD

**Issue by z954134** [MapWindow/MapWindow5#24]
when i link postgis,chinese show error
 pgconnstr = "PG:host=localhost dbname=x user=postgres password=xxx";
            string sqlOrLayerName = "SELECT * x";
            int handle = map.AddLayerFromDatabase(pgconnstr, sqlOrLayerName, true);
How can I solve it?

**Comment by pmeems** [comment]
What is the error? Please post in English ;)
And MapWindow/MapWinGIS does not yet fully support UNICODE.

**Comment by z954134** [comment]
MapWinGIS does not yet fully support UNICODE?maybe this is the reason

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
