### ISSUE TITLE
Incorrect display of SLOVENE national characters from Spatialite

### ISSUE THREAD

**Issue by vzavec** [MapWindow/MapWindow5#25]
Hi there!

I am running MW5.1 application on Windows 10 with connection to spatialite db (utf-8). Layers are added from a spatialite database.

When change the Encoding of the streamreader:

            sr.Encoding = Encoding.GetEncoding(1250);

and write text to file then any special characters will be handled correctly. 

But this is not the case with MW5 when tried to show our characters in the Table Editor, as labels, as categories or in the identifier.

Is there any possibility that we can show UTF-8 encoded text from spatialite or from shape file in MapWindow5?

Thanks for help, Vojko

Shared publicly

**Comment by pmeems** [comment]
Hi Vojko,
It's a known limitation of MapWinGIS/MW5 that they can't fully handle unicode.
We have planned to solve this, but it is a large task. We already made some changes but not yet all.

Can you share a sample spatiaLite db so we have some test data?

Thanks.

**Comment by vzavec** [comment]
Hi Paul!

I am glad for your quick answer. Appended is GEOM.SQLITE with two tables: CEV (lines) and VH (points). Field OPIS and field ULICA both have text with our SLOVENE characters.

We are working in the field of GAS, HOTWATER, WATER and STEAM networks and hardly waiting when this problem will be solved.


Thanks and regards, Vojko




Sent from Mail for Windows 10

**Comment by pmeems** [comment]
Hi Vojko,

Your attachment was not added. Probably because you replied the mail. Can you go to the issue on GitHub and manually attach it?

Thanks,
Paul

**Comment by vzavec** [comment]
Hi there!
Here is spatialite db with two objects.
[GEOM.zip](https://github.com/MapWindow/MapWindow5/files/1728353/GEOM.zip)

Regards, Vojko

**Comment by vzavec** [comment]
Hi there!
Here is spatialite db with two objects:

[GEOM.zip](https://github.com/MapWindow/MapWindow5/files/1728364/GEOM.zip)

Regards, Vojko

**Comment by pmeems** [comment]
Thanks for the sample data.
I created https://mapwindow.atlassian.net/browse/MWGIS-112 for this.

**Comment by vzavec** [comment]
He there!
We are very interested on your work with SLOVENE characters. How long it will takes, is there any progres with this problem?

Regards, Vojko

**Comment by vzavec** [comment]
Hi there!

"Slovene characters are not properly displayed in MW5"

If you managed to find a solution regarding slovenian language within the MW5 app we could arrange a certain amount to be donated. Please suggest the approximate amount for the job.

Regards, Vojko

**Comment by pmeems** [comment]
Hi @vzavec can you send me an e-mail at info[at]mapwindow[D0T]nl? 
So we can discuss this more off-list?

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
