### ISSUE TITLE
MW5 Plugin

### ISSUE THREAD

**Issue by saadb** [MapWindow/MapWindow5#27]
Just wondering about the status of documentation for creating a plugin, that would be very much appreciated

**Comment by pmeems** [comment]
Did you have a look at the template plug-in. It should be more or less self-explanatory.
Let me know if you have specific questions.

**Comment by TongZhai** [comment]
@pmeems where is the template plug-in? I just download and installed the [latest version MapWindow5](https://github.com/MapWindow/MapWindow5/releases/download/v5.4.1/MapWindow-v5.4.1.0-x64.exe), I don't see any template plugin under plugin menu option or in my personal roaming directories.

**Comment by pmeems** [comment]
Because v5.4.1 is just a hotfix of v5.1.0 I have not included the template plug-in.
You get download it from the v5.1.0 page: https://github.com/MapWindow/MapWindow5/releases/tag/v5.4.0
