### ISSUE TITLE
MapWinGis mbtiles

### ISSUE THREAD

**Issue by pachoduran** [MapWindow/MapWindow5#28]
Hi, i neer your help, is posible use .mbtiles Maps in MapWinGIs over c# . Need Work with maps offline.

thanks, for your help.

Byee

**Comment by pmeems** [comment]
Do you mean you have a .mbtiles file and want to open it using MapWinGIS?
Can't you use the FileManager: http://www.mapwindow.org/documentation/mapwingis4.9/class_file_manager.html#details

BTW. No need to cross post MapWinGIS questions in the MW5 repo. I'm closing this issue.
