### ISSUE TITLE
Plugins for MapWindow5?

### ISSUE THREAD

**Issue by saraneh** [MapWindow/MapWindow5#29]
Hiya! Does anyone know of any downloadable plugins for MapWindow5?
There seems to be a lot of interesting ones that work for MapWindow4, but these cannot be opened in MapWindow 5.

**Comment by pmeems** [comment]
All available plug-ins, I'm aware of, are included in the MW5 installer.

**Comment by GEO-Alice** [comment]
Hi, 
I'm new with MapWindow but a pro user of ArcGis. I have two questions:
1-Can you tell me if is there is a way to do bookmark under the 5 version. I see that the 4 version could. Is there a plugin? 
2-Is there a way to group layer? example all the hydrant together (lake, stream, 
water basin, etc.)
best regards
