### ISSUE TITLE
MapWindow4 Plugin Porting to MW5

### ISSUE THREAD

**Issue by dhuantes** [MapWindow/MapWindow5#3]
Working my way through porting a plugin that I had under MapWindow4 and would be great if there was a cross reference of things like "In MapWindow4 Plugin the MapWinGIS reference is now replaced by...."  I really like the new plugin approach but nice reference doc would be great.  May start putting one together if not....  Thanks!

**Comment by saadb** [comment]
How is the Plugin doc going

**Comment by pmeems** [comment]
Hi @dhuantes did you manage to finish your plug-in and create some documentation?
