### ISSUE TITLE
plugin watershed delineation

### ISSUE THREAD

**Issue by GIAN362** [MapWindow/MapWindow5#31]
Good morning, I installed mapwindow 5 because I should calculate the area of a river basin with the plugin watershed delineation. After the installation, however, under the menu plugins only appears to me "configure plugins ..." and I can not do anything. You can help me? Thank you.

**Comment by pmeems** [comment]
The watershed delineation plug-in is not yet converted from MapWindow-v4 to MapWindow-v5.
This is because of lack of time. 
If you are a C# developer you can try it yourself or else you need to wait until somebody else will do it for you.
Having some budget might speed this process up a bit.
