### ISSUE TITLE
Projection

### ISSUE THREAD

**Issue by ultraTCS** [MapWindow/MapWindow5#32]
Reprojecting shapefiles issues...

I've set the map projection to be WGS 84 / Pseudo-Mercator (EPSG 3857).
I add a shapefile layer with projection WGS 84 (EPSG 4326).

The reprojection tool fails. I get the following messages:
![reproject_debug](https://user-images.githubusercontent.com/24417284/38740222-8d1ad1f0-3f26-11e8-9b53-57be65c5f92e.JPG)

If instead I set map projection to be WGS 84 (EPSG 4326) and then open the shapefile with same projection and then Reproject shapefile to Mercator (EPSG 3857), the app can crash or I get a similar result:

![capture](https://user-images.githubusercontent.com/24417284/38740583-74f12e0c-3f27-11e8-8484-6057acad689d.JPG)

Here is the shapefile with default prj.
[countries.zip](https://github.com/MapWindow/MapWindow5/files/1907766/countries.zip)

**Comment by pmeems** [comment]
Your zip-file doesn't contain a .dfb-file.
That might also explain the error about the table.
