### ISSUE TITLE
Legend docking panel disappeared

### ISSUE THREAD

**Issue by sempreproblemi** [MapWindow/MapWindow5#35]
I closed the Legend docking panel and now I'm unable to find a way to show it again. I also closed the Identifier docking panel but, in this case, it appears again if I query a vector object. I tried to uninstall and reinstall but the problem remains. Thanks for any help.

Claudio

**Comment by pmeems** [comment]
You could go to `%AppData%\MapWindow5` and remove `mwconfig.xml`
Next restart MW5 and the panels should be restored.

Let me know if this solves your issue. If so I'll make a feature request to be able to do this within MW5.

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
