### ISSUE TITLE
Castle.Core could not be loaded

### ISSUE THREAD

**Issue by saadb** [MapWindow/MapWindow5#37]
Description: Could not load file or assembly 'Castle.Core, Version=4.1.1.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The system cannot find the file specified.

Stack trace: 
   at Castle.MicroKernel.DefaultKernel..ctor(IDependencyResolver resolver, IProxyFactory proxyFactory)
   at Castle.MicroKernel.DefaultKernel..ctor()
   at Castle.Windsor.WindsorContainer..ctor()
   at MW5.DI.Castle.WindsorCastleContainer..ctor()
   at MW5.Program.Main()

Description: Could not load file or assembly 'Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The system cannot find the file specified.

Stack trace:

**Comment by pmeems** [comment]
When do you get this message?

- Are you running MapWindow5 using the downloaded installer?

- Did you build MW5 from source?

**Comment by saadb** [comment]
I pulled the source code and compiled it in VS2017 successuflly, and when I run Mapwindow5.exe I get the above run time error

**Comment by saadb** [comment]
By the way I am using VS2017 Community Edition

**Comment by pmeems** [comment]
We build MW5 and MapWinGIS using VS2015 Community ourself.
Perhaps you are using a different package? We're using v4.1.1 of Castle.Core. We've not yet upgraded.

You did pull from the dev branch?

**Comment by saadb** [comment]
Yes, I pulled the dev branch
When I roll Castle.Core from 4.3.1 to 4.1.1 then no run time error related to Castle.Core

**Comment by pmeems** [comment]
So something changed between v4.3.1 and v4.1.1.
Are you up for a challenge to find out what we need to change to use the latest version of Castle?

--
Paul

**Comment by saadb** [comment]
Yes,
I will check it out

**Comment by saadb** [comment]
when using VS2017 run NuGet Package Manager for MW5.DI.Castle
Update castle.core to latest version (i.e v4.3.1) and Castle.Windsor (v4.1.0)
Make sure packages.config in the MW5.DI.Castle has been updated accordingly
Rebuild the soultion

**Comment by pmeems** [comment]
Is this the solution for this problem?
If so I can close this issue.

**Comment by saadb** [comment]
I suggest to keep this issue open for a little while, I am still chasing why the app.config is not syncing with packages.config and dependencies not updating accordingly.

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
