### ISSUE TITLE
MSSQL Add Geometry error

### ISSUE THREAD

**Issue by lepetitchu** [MapWindow/MapWindow5#40]
I have some spatial tables in **MS SQL Server**. When trying to draw new feature in MW5 with the tool **Add Geometry**, it can't be saved into database. The layer has a Primary-Key attribute name **OBJECTID**, MW5 doesn't let me edit that attribute, and it seems to set to NULL value when saving edit. Here's the sample data & screenshot of problem. Any solution? Thanks!
Data: [database.zip](https://github.com/MapWindow/MapWindow5/files/2708401/database.zip)

![mw_error mssql_add_geometry](https://user-images.githubusercontent.com/46039380/50417328-53590d00-0858-11e9-94a8-07a9aca3e4ce.png)

**Comment by mathijs-dumon** [comment]
Hey, this is a known bug in GDAL/OGR - it is fixed upstream. You'll have to either manually build GDAL, MapWinGIS and MapWindow (not easy) or wait for a new release

**Comment by pmeems** [comment]
@lepetitchu Can you check with the latest version of MapWindow if this is now fixed?

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
