### ISSUE TITLE
SelectByRectangle

### ISSUE THREAD

**Issue by JuntaoLi** [MapWindow/MapWindow5#46]
Hi,
System crash when I click feature by SelectByRectangle tool。
I looked at the MapWinGIS source code，found Shapefile_Selection.cpp-SelectShapeCore()-_shapeData[shapeVal]->shape is NULL

**Comment by wanghai1988** [comment]
mark

**Comment by pmeems** [comment]
Which version are you using and what data did you load and how can we reproduce.

**Comment by JuntaoLi** [comment]
> Which version are you using and what data did you load and how can we reproduce.

Hi,I am using MapWindow-5.4.0，add a shapefile (Polygon), click any feature by SelectByRectangle tool

**Comment by pmeems** [comment]
I just checked with the USA-sample data and I can confirm MW5 crashes.
We will investigate this and provide a fix soon.

Thanks for catching this.
I've created https://mapwindow.atlassian.net/browse/MW5CORE-218 for this.

**Comment by pmeems** [comment]
We've fixed the problem and I just published a new version of MapWindow5: https://github.com/MapWindow/MapWindow5/releases/
Please download and install it.

**Comment by wanghai1988** [comment]
> We've fixed the problem and I just published a new version of MapWindow5: https://github.com/MapWindow/MapWindow5/releases/
> Please download and install it.

OK thanks
