### ISSUE TITLE
Attribute Table

### ISSUE THREAD

**Issue by frznak** [MapWindow/MapWindow5#47]
version 5.3 would not show the attribute table when I tried to edit or access. It worked fine last fall, but an update to Windows 10 might have broke it. Upgraded to version 5.4 and still no attribute table but now when I try to find the information on a poly, mapwindow just closes.

**Comment by frznak** [comment]
I can open the table editor and gain access to the attribute table, but Mapwindow still closes (crashes) on me when I click on the info of a poly

**Comment by pmeems** [comment]
The `select` function has a bug, which is fixed at this moment. A new installer will be created shortly.

**Comment by pmeems** [comment]
New installer is available.
I close this issue.
