### ISSUE TITLE
Longitude display error.

### ISSUE THREAD

**Issue by geomatixDeveloper** [MapWindow/MapWindow5#49]
On Mapwingis there is a longitude display error, which alos seems to upset tile loading of background maps. It s present in 4.9.6.1 and in 5.0.1.0
Set Map1.ShowCoordinates=true
The default latitude and longitude is degrees and minutes
However using this default map  set-up when the cursor is just in the west the values the map is displaying -ve minutes with positive degrees. I guess its a bug in the display conversion routine.
Using W7 and VB6. You can see this easily if you display a background map and pan it to London UK which is on the Grenwich meridan. Then move the cursor slowly from right to left. It changes from Lng: 0° 00 ' to -1° 59' which is incorrect it should read -0° 01'. A similar bug seems to affect the tiles which are refreshed and loaded. The result is that tiles to the west are not updated properly and display in lo-res than those on the right.
![image](https://user-images.githubusercontent.com/51410318/58962895-09c80300-87a4-11e9-9804-bb8f564e2e9b.png)

**Comment by pmeems** [comment]
Thanks for letting us know.
We will investigate this more. At the moment we have some problems loading any OSM tiles, we need to fix that first.

**Comment by jeske** [comment]
possibly related to this?

https://github.com/MapWindow/MapWindow5/issues/55

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
