### ISSUE TITLE
Getting started with MapWinGIS 4.9.3+ --> Not working as stated.

### ISSUE THREAD

**Issue by nframpton** [MapWindow/MapWindow5#50]
I have followed the instructions to:
- Download and Install MapWinGIS - Win32
- Added it to my form
- Adjust the KnowExtents to keUSA
- Set my Lat/Long to (39.3718516, -76.3840588)  Zoom to 5
- Projection to GOOGLE_MERCATOR
- Grab Projection from Data to True
Result --> A white tile with no data around my lat and long
Is there additional properties that need adjusted?  A sample project so that you could compare the OCX properties solves a-lot of this type of startup issue.
Thanks for any help!  I am using Visual Studio 2017 using C# Win Forms

**Comment by pmeems** [comment]
Do you really need v4.9.3? Can't you upgrade to v5?
It looks like the issue we had with OSM tiles and which was solved a few days ago.
Please have a look at this forum post: https://mapwindow.discourse.group/t/openstreetmap-tiles-and-5-0-1-1/180/12

It is also better to ask questions at that forum than here.
