### ISSUE TITLE
Dynamic Projection  like arcgis

### ISSUE THREAD

**Issue by ccxxbb** [MapWindow/MapWindow5#54]
When loading the layers in different coordinate systems of data frame, can we display them by dynamic projection without generating new files?   thanks

**Comment by pmeems** [comment]
MW5 will create new files which are reprojected. When you next time reload the shapefile it will not be reprojected again but the cached file will be used.
MapWinGIS does make an in-memory reprojected shapefile, which you need to save manually (if needed).

Please post questions at our forum: https://mapwindow.discourse.group/
I'm closing this question.
