### ISSUE TITLE
hover longitude doesn't match raster inspection longitude

### ISSUE THREAD

**Issue by jeske** [MapWindow/MapWindow5#55]
In MapWindow 5, the"mouse hover longitude" doesn't match the "raster info" tool longitude for the same point.

Despite my labels on this ([Lake Tahoe data](https://pubs.usgs.gov/dds/dds-55/pacmaps/lt_data.htm)), I've now decided none of the lat/long values seem correct, but the raster-info inspection panel values seem "closer to correct"

![image](https://user-images.githubusercontent.com/15093/61591467-0d5cf100-ab7c-11e9-9316-e4ceb5570217.png)

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
