### ISSUE TITLE
Hover latitude incorrect in southern hemisphere

### ISSUE THREAD

**Issue by eganchris** [MapWindow/MapWindow5#56]
[map_window_points.zip](https://github.com/MapWindow/MapWindow5/files/3430344/map_window_points.zip)

The latitude is shown correctly as -38 00 00 for a point with this value.
But a latitude with minutes is shown incorrectly -  eg  -38 03  is shown as  -39 57
The longitude value is shown correctly

**Comment by pmeems** [comment]
If this is still an issue with the latest release (https://github.com/MapWindow/MapWindow5/releases) could you create a new issue?
For now, I close this old issue.
