### ISSUE TITLE
Wrong visualization of OpenStreetMap, Bing maps, ...

### ISSUE THREAD

**Issue by pglira** [MapWindow/MapWindow5#8]
There seems to be an issue with the visualization of OpenStreetMap, Bing maps, ... - see here:
![2017_01_31_19_06_51](https://cloud.githubusercontent.com/assets/14214284/22478051/a5d4a3c4-e7e8-11e6-95c1-5239ec18ac02.png)

**Comment by pmeems** [comment]
This happens because you use a different projection (Lambert-93) than the tiles are made in (Google Mercator). MW5 reproject the tiles on the fly for you, which will create distortions.

**Comment by pmeems** [comment]
Since no new replies I close this issue.
