### ISSUE TITLE
Api.Concrete.Coordinate Constructor

### ISSUE THREAD

**Issue by dhuantes** [MapWindow/MapWindow5#9]
My plugin uses Z values in all shape files.  But the Coordinate class only provides a single constructor that only allows X and Y values to be passed in.  So I have to call it and then separately assign the Z value using the Z property.  Would prefer to have another constructor that would allow me to pass in the Z values as well.

**Comment by pmeems** [comment]
I created an issue about this here: https://mapwindow.atlassian.net/browse/CORE-191
And added a constructor which takes 3 double: https://github.com/mapwindow/MapWindow5/commit/41da5ee5350c00ed3b0a488ef5c236e453003204
