### ISSUE TITLE
Resolution cannot be adaptive

### ISSUE THREAD

**Issue by chinashushi** [MapWindow/MapWindow5#90]
When the computer resolution is 100%，the software shows no problem。But，When the computer resolution is 150%，software views will shrink， and cannot be enlarged。

**Comment by mathijs-dumon** [comment]
You can fix this by overriding the high-DPI scaling settings in windows.
1. right click the MW5 executable and go to properties
2. open the compatibility tab
3. click "Change settings for all users"
4. click on "Change high-DPI settings"
5. check the box as in the screenshot and set the drop-down to Application
![image](https://user-images.githubusercontent.com/364371/114933670-38e83a80-9e39-11eb-8ac4-2b403e06ce3c.png)
